openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/admin/book-categories:
    get:
      summary: 'Get all Book Categories.'
      operationId: getAllBookCategories
      description: ''
      parameters:
        -
          in: query
          name: 'filter[title]'
          description: 'filter Book Categroies by title.'
          example: nihil
          required: false
          schema:
            type: string
            description: 'filter Book Categroies by title.'
            example: nihil
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 20
                      title:
                        ar: 'Enim non.'
                        en: 'Saepe est.'
                    -
                      id: 19
                      title:
                        ar: Quasi.
                        en: 'Vitae eum.'
                    -
                      id: 18
                      title:
                        ar: 'Ut maxime.'
                        en: Velit.
                    -
                      id: 17
                      title:
                        ar: Sit.
                        en: Illum.
                    -
                      id: 16
                      title:
                        ar: 'Totam sed.'
                        en: Molestiae.
                    -
                      id: 15
                      title:
                        ar: Sunt.
                        en: In.
                    -
                      id: 14
                      title:
                        ar: Deleniti.
                        en: 'Ab et.'
                    -
                      id: 13
                      title:
                        ar: Sint.
                        en: Sunt.
                    -
                      id: 12
                      title:
                        ar: Quam.
                        en: 'Nisi sunt.'
                    -
                      id: 11
                      title:
                        ar: 'Vel aut.'
                        en: Quod.
                    -
                      id: 10
                      title:
                        ar: Totam.
                        en: Doloribus.
                    -
                      id: 9
                      title:
                        ar: 'Unde et.'
                        en: Est.
                    -
                      id: 8
                      title:
                        ar: Deserunt.
                        en: Error.
                    -
                      id: 7
                      title:
                        ar: 'Et ut et.'
                        en: 'Rerum quo.'
                    -
                      id: 6
                      title:
                        ar: Maxime.
                        en: 'Ut maxime.'
                  links:
                    first: 'http://localhost/api/admin/book-categories?page=1'
                    last: 'http://localhost/api/admin/book-categories?page=2'
                    prev: null
                    next: 'http://localhost/api/admin/book-categories?page=2'
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 2
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/admin/book-categories?page=1'
                        label: '1'
                        active: true
                      -
                        url: 'http://localhost/api/admin/book-categories?page=2'
                        label: '2'
                        active: false
                      -
                        url: 'http://localhost/api/admin/book-categories?page=2'
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost/api/admin/book-categories'
                    per_page: 15
                    to: 15
                    total: 20
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 20
                        title:
                          ar: 'Enim non.'
                          en: 'Saepe est.'
                      -
                        id: 19
                        title:
                          ar: Quasi.
                          en: 'Vitae eum.'
                      -
                        id: 18
                        title:
                          ar: 'Ut maxime.'
                          en: Velit.
                      -
                        id: 17
                        title:
                          ar: Sit.
                          en: Illum.
                      -
                        id: 16
                        title:
                          ar: 'Totam sed.'
                          en: Molestiae.
                      -
                        id: 15
                        title:
                          ar: Sunt.
                          en: In.
                      -
                        id: 14
                        title:
                          ar: Deleniti.
                          en: 'Ab et.'
                      -
                        id: 13
                        title:
                          ar: Sint.
                          en: Sunt.
                      -
                        id: 12
                        title:
                          ar: Quam.
                          en: 'Nisi sunt.'
                      -
                        id: 11
                        title:
                          ar: 'Vel aut.'
                          en: Quod.
                      -
                        id: 10
                        title:
                          ar: Totam.
                          en: Doloribus.
                      -
                        id: 9
                        title:
                          ar: 'Unde et.'
                          en: Est.
                      -
                        id: 8
                        title:
                          ar: Deserunt.
                          en: Error.
                      -
                        id: 7
                        title:
                          ar: 'Et ut et.'
                          en: 'Rerum quo.'
                      -
                        id: 6
                        title:
                          ar: Maxime.
                          en: 'Ut maxime.'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 20
                        title:
                          type: object
                          properties:
                            ar:
                              type: string
                              example: 'Enim non.'
                            en:
                              type: string
                              example: 'Saepe est.'
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost/api/admin/book-categories?page=1'
                      last:
                        type: string
                        example: 'http://localhost/api/admin/book-categories?page=2'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: 'http://localhost/api/admin/book-categories?page=2'
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 2
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost/api/admin/book-categories?page=1'
                            label: '1'
                            active: true
                          -
                            url: 'http://localhost/api/admin/book-categories?page=2'
                            label: '2'
                            active: false
                          -
                            url: 'http://localhost/api/admin/book-categories?page=2'
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost/api/admin/book-categories'
                      per_page:
                        type: integer
                        example: 15
                      to:
                        type: integer
                        example: 15
                      total:
                        type: integer
                        example: 20
      tags:
        - 'Admin Endpoints'
      security: []
    post:
      summary: 'Store Book Category.'
      operationId: storeBookCategory
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Admin Endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: array
                  description: 'The title of the Book Category.'
                  example:
                    en: Historical
                    ar: تاريخي
                  items:
                    type: string
              required:
                - title
      security: []
    parameters:
      -
        in: path
        name: page
        description: 'The page number'
        example: 1
        required: true
        schema:
          type: integer
      -
        in: path
        name: perPage
        description: 'Number of items pre page'
        example: 3
        required: true
        schema:
          type: integer
  '/api/admin/book-categories/{id}':
    get:
      summary: 'Get Book Category by id.'
      operationId: getBookCategoryById
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 14
                    title:
                      ar: Deleniti.
                      en: 'Ab et.'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 14
                      title:
                        type: object
                        properties:
                          ar:
                            type: string
                            example: Deleniti.
                          en:
                            type: string
                            example: 'Ab et.'
      tags:
        - 'Admin Endpoints'
      security: []
    put:
      summary: 'Update Book Category.'
      operationId: updateBookCategory
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Admin Endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: array
                  description: 'The title of the Book Category.'
                  example:
                    en: Historical
                    ar: تاريخي
                  items:
                    type: string
              required:
                - title
      security: []
    delete:
      summary: 'Delete Book Category.'
      operationId: deleteBookCategory
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Admin Endpoints'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the book category'
        example: 14
        required: true
        schema:
          type: integer
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: ''
                  example: qui
                password:
                  type: string
                  description: ''
                  example: '-0QKN2['
              required:
                - username
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/book-categories:
    get:
      summary: 'Get all Book Categories.'
      operationId: getAllBookCategories
      description: ''
      parameters:
        -
          in: header
          name: lang
          description: ''
          example: ar
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 20
                      title: 'Enim non.'
                    -
                      id: 19
                      title: Quasi.
                    -
                      id: 18
                      title: 'Ut maxime.'
                    -
                      id: 17
                      title: Sit.
                    -
                      id: 16
                      title: 'Totam sed.'
                    -
                      id: 15
                      title: Sunt.
                    -
                      id: 14
                      title: Deleniti.
                    -
                      id: 13
                      title: Sint.
                    -
                      id: 12
                      title: Quam.
                    -
                      id: 11
                      title: 'Vel aut.'
                    -
                      id: 10
                      title: Totam.
                    -
                      id: 9
                      title: 'Unde et.'
                    -
                      id: 8
                      title: Deserunt.
                    -
                      id: 7
                      title: 'Et ut et.'
                    -
                      id: 6
                      title: Maxime.
                    -
                      id: 5
                      title: 'Nam sit.'
                    -
                      id: 4
                      title: Saepe.
                    -
                      id: 3
                      title: Vel.
                    -
                      id: 2
                      title: Possimus.
                    -
                      id: 1
                      title: Molestiae.
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 20
                        title: 'Enim non.'
                      -
                        id: 19
                        title: Quasi.
                      -
                        id: 18
                        title: 'Ut maxime.'
                      -
                        id: 17
                        title: Sit.
                      -
                        id: 16
                        title: 'Totam sed.'
                      -
                        id: 15
                        title: Sunt.
                      -
                        id: 14
                        title: Deleniti.
                      -
                        id: 13
                        title: Sint.
                      -
                        id: 12
                        title: Quam.
                      -
                        id: 11
                        title: 'Vel aut.'
                      -
                        id: 10
                        title: Totam.
                      -
                        id: 9
                        title: 'Unde et.'
                      -
                        id: 8
                        title: Deserunt.
                      -
                        id: 7
                        title: 'Et ut et.'
                      -
                        id: 6
                        title: Maxime.
                      -
                        id: 5
                        title: 'Nam sit.'
                      -
                        id: 4
                        title: Saepe.
                      -
                        id: 3
                        title: Vel.
                      -
                        id: 2
                        title: Possimus.
                      -
                        id: 1
                        title: Molestiae.
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 20
                        title:
                          type: string
                          example: 'Enim non.'
      tags:
        - 'Public Endpoints'
      security: []
tags:
  -
    name: 'Admin Endpoints'
    description: ''
  -
    name: Endpoints
    description: ''
  -
    name: 'Public Endpoints'
    description: ''
